services:
  - type: worker
    name: gasham-bot
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node --max-old-space-size=512 index.js
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OWNER_NUMBER
        value: ""
    autoDeploy: false
    plan: free
